### PR TITLE
added 1606 and 0405 JWST data

### PR DESCRIPTION
**Pull request by rekeeley**
I've been running the example_script_no_image_data_0405.py and example_script_no_image_data_1606.py scripts.  They seem to run without error but its worth checking everything's reasonable.

### CODE REVIEW

**Comment by dangilman** [comment]
Hi @rekeeley, looks good. Before I merge into the master branch, would you mind removing the commented-out satellite galaxy lines at the end of the data files?

**Comment by rekeeley** [comment]
I've now removed those commented out lines -Ryan

**Review by dangilman — APPROVED** [review]

**Comment by dangilman** [comment]
@rekeeley, thanks it looks good now. there seems to be a merge conflict for psj1606 that is blocking the integration with the main branch, probably because I added the imaging data for this system and updated the data and model files

**Comment by rekeeley** [comment]
I renamed the psj1606 data file to psj1606_noImaging. Does that resolve the
conflict?

**Comment by dangilman** [comment]
@rekeeley, no apparently it's still there. However, I don't think you actually need to change anything for psj1606 file from whats on the master branch. is there a reason you created a new file for it?

**Pull request merged**
